spring.application.name=mongo-semantic-search

spring.ai.openai.api-key=${OPENAI_API_KEY:}
spring.ai.openai.embedding.options.model=text-embedding-ada-002


#spring.data.mongodb.uri=mongodb://murad:password@localhost:27017
spring.data.mongodb.uri=mongodb+srv://murad:Db99912357#@cluster0.jx83t.mongodb.net/
spring.data.mongodb.database=doctor_db
spring.ai.vectorstore.mongodb.indexName=vector_index
spring.ai.vectorstore.mongodb.collection-name=vector_store
#spring.ai.vectorstore.mongodb.initialize-schema=true

server.port=8083

spring.profiles.active=dev